---
abstract: Abstract
author:
  - 'Abigail <cpan@abigail.be>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
keywords: []
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MetaSyntactic-Themes-Abigail
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/Abigail/Acme-MetaSyntactic-Themes-Abigail.git
version: 2012051701
x_test_requires:
  Test::More: 0.88
  strict: 0
  warnings: 0
